[all_follow]
nixpkgs = "nixpkgs"

[inputs.disko]
url = "gh:nix-community/disko?ref=master"

[inputs.flake-parts]
url = "gh:hercules/flake-parts?ref=main"

[inputs.hjem]
url = "gh:feel-co/hjem?ref=main"

[inputs.hyprland-scroll-overview]
type = "fetch"
url = "gh:yayuuu/hyprland-scroll-overview"

[inputs.import-tree]
url = "gh:denful/import-tree?ref=main"

[inputs.nixpkgs]
url = "gh:nixos/nixpkgs?ref=nixos-unstable"

[inputs.nur]
url = "gh:nix-community/NUR?ref=master"

[inputs.tack]
url = "gh:manic-systems/tack"

[shorturls]
gh = "github:{path}"
